export * from './Header.tsx'
export * from './ProfessorCard.tsx'
export * from './DeleteProfessorCommentPopup.tsx'
export * from './AddProfessorCommentPopup.tsx'
export * from './UpdateProfessorCommentPopup.tsx'